source $VIM/_vimrc

"""""""" vundle stuff """""""""
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/vimfiles/bundle/Vundle.vim/
let path='~/vimfiles/bundle'
call vundle#begin(path)
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
Plugin 'jnurmine/Zenburn'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdtree'
Plugin 'msanders/snipmate.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'altercation/vim-colors-solarized'
Plugin 'PProvost/vim-ps1'
Plugin 'kien/ctrlp.vim'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
"Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line
"
"""""""""""""""" end vundle stuff """""""""""""""""""""

"execute pathogen#infect()

filetype plugin indent on

"
" My customizations --RMV
"
source $HOME\_vimrc_functions

set backup
set backupdir=$HOME\tmp
set dir=$HOME\tmp
set number
set cursorline
set hidden "allows the ability to switch buffers without being forced to use '!'
set guifont=Lucida_console:h12
set columns=120
set lines=35
syntax enable

	"appearance settings
highlight Cursorline ctermbg=white
set background=light
colorscheme solarized

	"tab behavior settings
set ts=4 sw=4 sts=4 expandtab

	"custom key mappings
"map Space and Shift-Space to jump forward and backward in the text
    nnoremap <Space> <C-f>
    nnoremap <S-Space> <C-b>
    nnoremap <Backspace> <C-b>
    vnoremap <Space> <C-f>
    vnoremap <S-Space> <C-b>
    vnoremap <Backspace> <C-b>

"maps Ctrl-n to open/close the NERDTree file explorer (try it now!)
    map <C-n> :NERDTreeToggle<cr>

"maps Ctrl-h/l or Ctrl-Leftarrow/Rightarrow to cycle through open buffers
    noremap <C-l> :bn<cr>
    noremap <C-h> :bp<cr>
    noremap <C-Right> :bn<cr>
    noremap <C-Left> :bp<cr>

"maps the arrow keys to jump to different split windows
    noremap <Up> <C-w>k
    noremap <Down> <C-w>j
    noremap <Left> <C-w>h
    noremap <Right> <C-w>l

"maps F12 to open vimrc
    map <F12> :execute OpenVimRC()<cr>

"maps F5 to run :make
    map <F5> :make<cr>

autocmd Filetype cpp execute Cpp()
autocmd Filetype python execute Python()

cd $HOME

" DONE!!
"
